### PR TITLE
updated to triton v2 api and tensorflow v2

### PR DESCRIPTION
**Pull request by mhlswang**

### CODE REVIEW

**Comment by lgarren** [comment]
There is a problem with ups/product_deps.  tensorflow and triton should be included in the debug setup with the same qualifiers used for prof.  I'm going to go ahead and trigger the build anyway since that problem can be fixed when merging.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by gartung** [comment]
trigger build

**Comment by lgarren** [comment]
We're going to need an accompanying PR for larpandoracontent that uses libtorch v1_6_0b.   It's a matter of using the same release of protobuf in the dependency tree.

**Comment by lgarren** [comment]
LArSoft/larpandoracontent#23 is needed to resolve the protobuf dependency mismatch.

**Comment by gartung** [comment]
trigger build with https://github.com/LArSoft/larpandoracontent/pull/23

**Comment by gartung** [comment]
trigger build with pull request  LArSoft/larpandoracontent#23

**Comment by gartung** [comment]
trigger

**Comment by gartung** [comment]
trigger

**Comment by gartung** [comment]
Sorry for the noise. Trying GithubPullRequestBuilder.

**Comment by lgarren** [comment]
trigger

testing infrastructure

**Comment by lgarren** [comment]
Reporting here that the explicitly triggered CI tests with both PRs appear to be OK.

**Comment by gartung** [comment]
code-checks
this should be passed on to the cms-bot script

**Pull request merged**
