### PR TITLE
Save Mike and Lorenzo's 1dcnn ROI finder results to recob::Wire.

### PR DESCRIPTION
**Pull request by yangtj207**

### CODE REVIEW

**Comment by yangtj207** [comment]
trigger build

**Comment by tomjunk** [comment]
You could consider putting a break statement after the isroi=true; at line 194 of WaveformRoiFinder_module.cc. That way it doesn't keep searching after it has set isroi=true.  Also need some braces around that so both the isroi=true is executed and the break.  In general, putting the statement to execute on the same line as the if statement makes debugging harder because you cannot set a breakpoint at the isroi=true; statement.

**Comment by tomjunk** [comment]
approved

**Comment by yangtj207** [comment]
Thank you Tom!

**Comment by lgarren** [comment]
approve

**Pull request merged**
