### PR TITLE
Feature/cerati nu graph

### PR DESCRIPTION
**Pull request by cerati**
Integration of NuGraph in LArSoft, as presented at https://indico.fnal.gov/event/62438/.

This requires libtorch v2_1_1 and torch_scatter v2_1_2 which are both available in ups now.

Actual GNN model files are not provided as they are experiment-specific.

Note that a license file from https://github.com/delfrrr/delaunator-cpp is added to Delaunator folder. Please let me know if there is a better way to do this.

### CODE REVIEW

**Comment by lgarren** [comment]
See https://cdcvs.fnal.gov/redmine/issues/28493

**Comment by knoepfel** [comment]
@cerati, thanks for the PR.  We will act on this once we have a UPS product for `delaunator` (or the ROOT equivalent if that's sufficient).  We have a few more comments/questions that we will bring up later.

**Comment by cerati** [comment]
> @cerati, thanks for the PR. We will act on this once we have a UPS product for `delaunator` (or the ROOT equivalent if that's sufficient). We have a few more comments/questions that we will bring up later.

I still need to perform a couple of reproducibility checks but the root equivalent may be a good solution as well

**Comment by lgarren** [comment]
@cerati It will be great if the root solution works.  We would prefer not to add yet another product.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@cerati  See the c14 build failure

**Comment by cerati** [comment]
@lgarren I believe the commit above fixes the c14 failure

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@cerati  Oh crud.  There is a conflict in ups/product_deps.  You'll need to merge the head of develop.

**Comment by cerati** [comment]
@lgarren -- done. Hopefully no more conflicts

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
approve

**Pull request merged**
