### PR TITLE
Suppress storage of wire with no ROI

### PR DESCRIPTION
**Pull request by tejinc**

### CODE REVIEW

**Comment by knoepfel** [comment]
Thanks, @tejinc, for the PR.  Will this be a breaking change for current workflows?

**Comment by knoepfel** [comment]
trigger build

**Comment by tejinc** [comment]
Hi Kyle,
 This shouldn't change the current workflow. Wires without ROI are zeroed
and have no information to gain.

**Comment by tomjunk** [comment]
Approved

**Comment by gartung** [comment]
approve

**Pull request merged**
