### PR TITLE
Implement a common framework for writing CVN modules for different larsoft geometries

### PR DESCRIPTION
**Pull request by nitish-nayak**
Aims to integrate the DUNE CVN pre-processing infrastructure into larrecodnn. In the process, also rationalizes some of the dune code. 

- Common framework for producing pixel maps by deriving from a base class, rather than rewriting and adding
- Better structures for saving auxillary information for training 

More details are given here : https://indico.fnal.gov/event/56692/contributions/252666/attachments/160682/211783/10_18_22_larcvn.pdf

### CODE REVIEW

**Comment by mhlswang** [comment]
Hi, I notice that you are using your own version of the TF interface in tf_graph.cc and tf_graph.h which was likely derived from the original one from larsoft by Robert Sulej et al. (now in larrecodnn) when CVN was ported to DUNE by Saul M. and Leigh W.  I suggest using the TF interface that is already in larrecodnn to avoid duplication.  I also suggest using the tool interface.  For an example, please look at how this is done for EmTrackMichelId:  see e.g. ./ToolsInterfaces/IPointIdAlg.h, ./Tensorflow/Tools/PointIdAlgTf_tool.cc, and ./Triton/Tools/PointIdAlgSonicTriton_tool.cc.  In this case for EmTrackMichelId, two separate tool interfaces are proviced, one for Tf and and one for SonicTriton.

**Comment by lgarren** [comment]
@nitish-nayak Please address Mike's comments: https://github.com/LArSoft/larrecodnn/pull/34#issuecomment-1290852117

**Comment by nitish-nayak** [comment]
Hi Mike, thanks! Yes, this is indeed what was ported to DUNE by Saul and Leigh. I am not too familiar with this part of the code but I'll take a look

**Comment by yangtj207** [comment]
@nitish-nayak Mike suggested you remove the tf_graph.cc and tf_graph.h in the CVN directory and instead use the one in larrecodnn/ImagePatternAlgs/Tensorflow/TF. Could you please do that? Thanks.

**Comment by nitish-nayak** [comment]
@yangtj207 the tf_graph files in ImagePatternAlgs currently don't handle the multiple inputs CVN has and there will need to be some modifications there. I'm also looking to change TFNetHandler.h [cxx] to make it into a tool like Mike suggested. Hopefully, this should all be done by tomorrow.

**Comment by nitish-nayak** [comment]
@mhlswang I've modified the tf_graph to interface with CVN in my local and removed the ~duplicated version. I can commit those. 

About the tool interface, I actually don't know how to go about modifying the CMake configs for that purpose. I've tried looking at your examples but even though I understand what I need to change in the classes itself, I don't know how to go about changing the CMakeLists.txt files. Would you be okay with keeping it as is for now? If not, I'd need some help there.

**Comment by lgarren** [comment]
@nitish-nayak please commit and push what you have right now.  This will help us take a look.

**Comment by lgarren** [comment]
@nitish-nayak I have a second request.  I just realized that you did not make a feature branch for this PR.  Would you please close this PR and open a new one on a feature branch?   LArSoft procedures explicitly request that PRs be on feature branches.  Many thanks.

**Comment by mhlswang** [comment]
@nitish-nayak if you've already made the necessary modifications to the code to implement the tool interface and only need to know how to modify the CMakeLists, then, as Lynn suggested, please commit and push your changes and the CMake experts in the scisoft team like Lynn can help you with the CMakeLists.

**Comment by nitish-nayak** [comment]
alright, will do! thanks a lot! I'll close this PR now and open a new one

**Pull request closed without merging**
