### PR TITLE
new directory structure to separate tf, keras, and trtis

### PR DESCRIPTION
**Pull request by mhlswang**

### CODE REVIEW

**Comment by knoepfel** [comment]
A migration script is being developed to support the changes in this PR.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
Note that failures are expected, since this test was made without matching feature branches.

**Comment by lgarren** [comment]
feature/team_rearrange_larrecodnn is available for argoneutcode.  No changes are needed for dunetpc or uboone code.

**Comment by knoepfel** [comment]
code-checks

**Comment by lgarren** [comment]
This change is ready to go.  It will be accompanied by larsoft PR 17

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
manual build triggered
`trigger --build-delay 0 --cert /tmp/x509up_u1147 --version develop --workflow default_wf --revisions "LArSoft/larrecodnn#13 argoneutcode@feature/team_rearrange_larrecodnn" `

**Comment by lgarren** [comment]
The CI tests are fine.  Only argoneutcode requires a feature branch.

**Comment by lgarren** [comment]
approve

**Pull request merged**
