### PR TITLE
replaced hard-coded producer label for MCParticle in RawWaveformDump with fcl specified param

### PR DESCRIPTION
**Pull request by mhlswang**

### CODE REVIEW

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@mhlswang  Would you document the changes required in fcl files please?  Just add a comment here with the relevant information.

**Comment by mhlswang** [comment]
description of changes:
1. in the original code, the producer for MCParticles was hardcoded as 'largeant'.  In this PR, this has been replaced with the existing 'SimulationProducerLabel' fcl parameter.
2. a new SimChannelLabel fcl parameter was also introduced to differentiate the producers for MCParticles and SimChannels, which, in the case of the refactored larg4, unlike in the legacy larg4, no longer have the same producer.
3. the default values for the following fcl parameters specifying the producers have been changed to typical values for the refactored larg4 case:
    SimulationProducerLabel: from largeant -> larg4Main
    DigitModuleLabel: from daq -> simWire
    users should make sure these fcl parameters are set appropriately in their config files if necessary
4. the default value for the new fcl parameter SimChannelLabel is set to 'elecDrift'. Legacy larg4 users should make sure this is set to the same label as that of the producer for MCParticles, e.g. 'largeant'.

**Comment by knoepfel** [comment]
This PR can be approved subject to L2 approval.

**Comment by yangtj207** [comment]
+1

**Comment by lgarren** [comment]
approve

**Pull request merged**
