### PR TITLE
Use tensorflow v1_12_0.

### PR DESCRIPTION
**Pull request by yangtj207**

### CODE REVIEW

**Comment by yangtj207** [comment]
code-checks

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
The tests were triggered externally and are mostly fine.  ubooncode is behind and cannot be tested, but the unit tests are OK.

**Comment by lgarren** [comment]
approve

**Comment by lgarren** [comment]
I see that the tests were triggered again - but without the dunetpc branch.  We know that that build will fail.

**Comment by lgarren** [comment]
merged by hand into larsoft v08_47_00

**Pull request closed without merging**
