### PR TITLE
fix NuGraph vertex inference

### PR DESCRIPTION
**Pull request by cerati**
This PR is a bug fix in how the vertex inference result is retrieved from the list of NuGraph outputs.
Note that the vertex decoder functionality is turned off by default.

### CODE REVIEW

**Comment by lgarren** [comment]
@cerati  How soon do you need this? There may not be a release this week unless we make one just for this PR.  It's still unclear.

**Comment by cerati** [comment]
@lgarren it's not critical to have it in this week, so if this is the only PR we can wait for next week

**Comment by lgarren** [comment]
trigger build

**Comment by cerati** [comment]
I added one more commit to make it optional to look for truth information in case one wants to run on data.

**Review by knoepfel — COMMENTED** [review]
Changes look good, @cerati.  Only a couple suggested changes.

**Comment by cerati** [comment]
thank you @knoepfel , I accepted the suggestions

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@LArSoft/level-2-managers please review and approve or comment

**Comment by knoepfel** [comment]
trigger build

**Comment by tomjunk** [comment]
Approved -- looks fine.

**Comment by lgarren** [comment]
approve

**Pull request merged**
